version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8081:80"  # Cambié el puerto para no hacer conflicto con el puerto 8080
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
